### ISSUE TITLE
🐛 - Heroku Deployment

### ISSUE THREAD

**Issue by GCMO** [CodingZeal/redwood-template-app#112]
## Description

The latest deployment give an error. See following link https://redwood-template-app.herokuapp.com/
Possibly because of the heroku's latest changes with free accounts. 

## Reproduce

Steps to reproduce the behavior

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior

A clear and concise description of what you expected to happen

## Screenshots

If applicable add screenshots to help explain your problem

## Where found

Please complete the following information

## Additional context

Add any other context about the problem here

**Comment by craineum** [comment]
@GCMO Thanks for bringing this up. We are trying to figure out where we want to take this since Heroku removed free accounts. We will update this ticket when we have a better solution.

**Comment by craineum** [comment]
@archae0pteryx & @iameddieyayaya 
Let's try and find a free solution as a replacement for Heroku. Maybe fly.io? We can look at a few different options, then decide on a path

**Comment by craineum** [comment]
After looking at other services we found we still think Heroku is the best option for all the features we want in a development hosting provider. PR #129 Fixed the issues with it not working.
