### ISSUE TITLE
Add a "save and close" button for the profile edit

### ISSUE THREAD

**Issue by archae0pteryx** [CodingZeal/redwood-template-app#119]
Currently, on the profile edit page, clicking "save" instantly redirects you back to home. This is a horrible user experience...

As a user, I want to be able to save and stay on my profile edit page. A button labeled "save and close" in addition to the "save". When I click the save button, i want to stay on the page. When i click the "save and close" button i want to close the page.

**Comment by craineum** [comment]
I am good if we just have "save" that doesn't redirect and puts up a toast that says "Successfully saved your profile" or a failure message if it failed.
