### ISSUE TITLE
🧹 - Friendly Unique IDs for public facing use over auto-incrementing IDs

### ISSUE THREAD

**Issue by craineum** [CodingZeal/redwood-template-app#19]
## Description

IDs can be guessed and manipulated when passed via public interfaces. We should be using some form of UUID over auto incrementing IDs

## Affects

- All tables in the DB

## Consequences

Makes it easy for someone to guess our data structure

**Comment by archae0pteryx** [comment]
This is a good opportunity to just add the rest of the initial db schema. After which the migration files should be removed and regenerated as "init" migrations.
