### ISSUE TITLE
✨ Admin Roles

### ISSUE THREAD

**Issue by craineum** [CodingZeal/redwood-template-app#29]
## Story

**In order to manage roles for the application**
**As an application admin**
**I need a way to create, read, update, and delete roles**

## Acceptance Criteria

- CRUD operations for roles
- Pages should be only accessible to admins
- APIs should only be accessible to admins
- Deleting should only be able to occur if the role is not in use

## Notes

Use RedwoodJS scaffolding to create everything

**Comment by house9** [comment]
I created PR: https://github.com/CodingZeal/redwood-template-app/pull/42 which deals with the role deletions, I think we still need to do additional work like adding `createdAt` and `updatedAt` to `Role`?

Going to remove my self from this story but leave in "In Progress"
