### ISSUE TITLE
🧹 Research template generation with RedwoodJS

### ISSUE THREAD

**Issue by craineum** [CodingZeal/redwood-template-app#37]
## Description

We need to decide how to generate a template application instead of a fixed version one which is what we currently have. We can look at how Rails has implemented its templating system as a reference.

### Some requirements we the templating system needs to handle:

- Prompting for user input to establish key items (like roles or user atttributes)
- Running existing RedwoodJS generators
- Updating of existing deployments where they may have changed something
- A way to "eject"?

### Things should be able to answer:

- Can RedwoodJS generators be used for generating a whole application template?
- If not, how much work would it entail to create a templating engine in RedwoodJS?
- Are there any alternatives to generating an application that has up-to-date libraries?

**Comment by archae0pteryx** [comment]
Answers
- Yes they certainly can be used to generate an "opinionated" complete app.
- With full time development a usable / beta version can be completed within 14-30 days. Advanced features like a plugin system / optional config file to slightly tweak settings and eventually having a config to completely generate a custom app with avail options. Like, selecting an e2e library or preferred style library. This would be a great contrib to the community and could even become its own community in parallel.
- Other alternatives don't seem to exist.
