### ISSUE TITLE
🧹 Running unit tests

### ISSUE THREAD

**Issue by craineum** [CodingZeal/redwood-template-app#58]
## Description

Currently it doesn't run the data base and the developer has to manually run the db in another window via `yarn testdb` or via `yarn testdb:daemon`. It also defaults to `no-watch` which is contrary to RedwoodJS defaults.

To run tests, executing `yarn test` should launch the test database in daemon mode along with running the unit tests in "watch" mode. There should be an additional option to run `yarn test:nowatch`.

## Affects

- Developer testing workflows

## Consequences

We drift further from RedwoodJS established patterns

**Comment by archae0pteryx** [comment]
I adjusted this [already](https://github.com/CodingZeal/redwood-template-app/blob/bf3a6c4c1b5753816ff031a7f54534b1499e4e8a/package.json) and removed the no watch from the normal command. For the regular api tests, redwood is still handling the test db on it's own. Those scripts i added were just for playwright.
