### ISSUE TITLE
🧹 Lint should ignore graphql files

### ISSUE THREAD

**Issue by craineum** [CodingZeal/redwood-template-app#59]
## Description

Ignore `web/types/graphql.d.ts`

## Affects

- Developer linting workflow

## Consequences

Could get false linting issues. May mess up local developer environment if they try to resolve.

**Comment by house9** [comment]
I think this has been taken care of already, see: https://github.com/CodingZeal/redwood-template-app/blob/main/.eslintignore

```
api/types/*
web/types/*
./index.js
.vscode
tmp
```

**Comment by house9** [comment]
🤔 maybe still an issue, but with prettier not eslint?



![Image](https://user-images.githubusercontent.com/52154/194666433-bebeb7ab-54d7-46f8-bcba-13e605888a6c.png)
